### ISSUE TITLE
characters encoding input/output

### ISSUE THREAD

**Issue by EudesRobin** [EudesRobin/mux-mkv_srt#3]
some characters can't be encoded...

```
Traceback (most recent call last):
  File "mux.py", line 122, in <module>
    mux(os.path.normpath(arg),mkvmerge)
  File "mux.py", line 65, in mux
    print('working on '+outputfile)
  File "C:\Users\2Night\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2010' in position 126: character maps to <undefined>
```

> > Need to encode/decode everything with utf-8.

**Comment by EudesRobin** [comment]
source : sys.stdinput.encoding /  sys.stdinput.encoding = 'cp850' on windows ( = 'UTF-8' on Debian, so it's okay for unix distrib, I guess...).
